<?php

namespace Database\Seeders;

use App\Models\MindfulTactic;
use Illuminate\Database\Seeder;

class MindfulTacticSeeder extends Seeder
{
    public function run(): void
    {
        $tactics = [
            [
                'title' => 'Teknik STOP',
                'category' => 'stop_technique',
                'description' => 'Jeda cepat untuk berhenti, bernapas, mengamati diri, lalu memilih respons dengan sadar.',
                'knowledge' => 'STOP membantu memberi jarak antara stimulus dan respons. Teknik ini cocok saat emosi naik, pikiran penuh, atau sebelum mengambil keputusan di kelas maupun saat belajar.',
                'duration_minutes' => 2,
                'steps' => [
                    'Stop: hentikan aktivitas sejenak dan diamkan tubuh.',
                    'Take a breath: tarik dan hembuskan napas perlahan.',
                    'Observe: amati tubuh, pikiran, emosi, dan dorongan yang muncul.',
                    'Proceed: lanjutkan dengan satu tindakan yang lebih sadar.',
                ],
                'cues' => ['Berhenti', 'Bernapas', 'Mengamati', 'Melanjutkan'],
                'best_for' => ['marah', 'cemas', 'konflik', 'reaksi impulsif'],
                'sort_order' => 1,
            ],
            [
                'title' => 'Grounding 3-2-1',
                'category' => 'grounding_321',
                'description' => 'Mengembalikan perhatian ke saat ini melalui hal yang dilihat, didengar, dan dirasakan.',
                'knowledge' => 'Grounding membantu saat pikiran terasa terlalu ramai atau tubuh mulai panik. Fokus sensorik membuat perhatian kembali ke lingkungan nyata, bukan hanya kekhawatiran di kepala.',
                'duration_minutes' => 3,
                'steps' => [
                    'Sebutkan tiga hal yang terlihat di sekitar.',
                    'Sebutkan dua suara yang terdengar saat ini.',
                    'Sebutkan satu sensasi fisik yang terasa paling jelas.',
                    'Tarik napas pelan dan lihat apakah tubuh mulai lebih menetap.',
                ],
                'cues' => ['Lihat', 'Dengar', 'Rasakan', 'Tenangkan'],
                'best_for' => ['cemas', 'panik', 'kewalahan', 'krisis'],
                'sort_order' => 2,
            ],
            [
                'title' => 'Napas 4-7-8',
                'category' => 'breathing_478',
                'description' => 'Tarik napas 4 detik, tahan 7 detik, lalu buang napas 8 detik.',
                'knowledge' => 'Latihan napas 4-7-8 dari website lama dipakai untuk menurunkan ketegangan tubuh secara bertahap. Ritme hembusan yang lebih panjang membantu tubuh masuk ke mode lebih tenang.',
                'duration_minutes' => 5,
                'steps' => [
                    'Duduk nyaman dan rilekskan bahu.',
                    'Tarik napas lewat hidung selama 4 hitungan.',
                    'Tahan napas dengan lembut selama 7 hitungan.',
                    'Hembuskan perlahan selama 8 hitungan.',
                    'Ulangi sampai waktu latihan selesai.',
                ],
                'cues' => ['Tarik 4', 'Tahan 7', 'Buang 8', 'Ulangi'],
                'best_for' => ['cemas', 'sulit tidur', 'tegang', 'stres'],
                'sort_order' => 3,
            ],
            [
                'title' => 'Jeda Napas 3 Menit',
                'category' => 'breathing_space_3min',
                'description' => 'Tiga menit untuk menyadari kondisi, fokus ke napas, lalu memperluas perhatian ke tubuh.',
                'knowledge' => '3-Minute Breathing Space adalah latihan ringkas dari pendekatan MBSR/MBCT. Latihan ini cocok sebagai transisi sebelum kelas, setelah aktivitas berat, atau ketika jurnal menunjukkan tekanan mulai muncul.',
                'duration_minutes' => 3,
                'steps' => [
                    'Menit pertama: sadari apa yang sedang dirasakan tanpa menghakimi.',
                    'Menit kedua: fokuskan perhatian ke napas masuk dan keluar.',
                    'Menit ketiga: perluas kesadaran ke seluruh tubuh.',
                    'Tutup dengan niat sederhana untuk aktivitas berikutnya.',
                ],
                'cues' => ['Sadari', 'Napas', 'Perluas', 'Niat'],
                'best_for' => ['transisi aktivitas', 'fokus', 'tekanan ringan'],
                'sort_order' => 4,
            ],
            [
                'title' => 'Awareness of Breathing',
                'category' => 'maintain_breath_awareness',
                'description' => 'Menjaga perhatian pada napas natural tanpa perlu mengubahnya.',
                'knowledge' => 'Latihan ini melatih hadir penuh dengan sikap non-striving: tidak memaksa hasil tertentu, cukup mengenali napas dan kembali saat perhatian berpindah.',
                'duration_minutes' => 3,
                'steps' => [
                    'Duduk stabil dengan punggung nyaman.',
                    'Rasakan napas masuk sebagaimana adanya.',
                    'Rasakan napas keluar sebagaimana adanya.',
                    'Saat terdistraksi, sadari lalu kembali ke napas.',
                    'Akhiri dengan satu napas panjang.',
                ],
                'cues' => ['Duduk', 'Napas masuk', 'Napas keluar', 'Kembali'],
                'best_for' => ['fokus', 'tenang', 'ritme stabil'],
                'sort_order' => 5,
            ],
            [
                'title' => 'Mindful Breathing',
                'category' => 'mindful_breathing',
                'description' => 'Menggunakan napas sebagai anchor perhatian tanpa memaksa napas berubah.',
                'knowledge' => 'Mindful Breathing mengembalikan fokus ke saat ini, memberi jeda setelah aktivitas, dan melatih konsentrasi. Teknik ini cocok untuk latihan awal sebelum teknik mindfulness lain.',
                'duration_minutes' => 5,
                'steps' => [
                    'Duduk atau berdiri dengan nyaman dan lepaskan ketegangan yang tidak perlu.',
                    'Perhatikan napas masuk dan napas keluar sebagaimana adanya.',
                    'Jika perhatian berpindah, sadari lalu kembali perlahan pada napas.',
                    'Akhiri dengan menyadari tubuh dan lingkungan.',
                ],
                'cues' => ['Persiapan', 'Sadari napas', 'Kembali', 'Penutup'],
                'best_for' => ['sulit fokus', 'stres ringan', 'pikiran ramai', 'jeda setelah aktivitas'],
                'sort_order' => 6,
            ],
            [
                'title' => 'Focused Attention Meditation',
                'category' => 'focused_attention',
                'description' => 'Mempertahankan perhatian pada satu anchor seperti napas, telapak kaki, telapak tangan, atau suara stabil.',
                'knowledge' => 'Focused Attention melatih kemampuan mempertahankan fokus dan kembali dari distraksi. Teknik ini cocok untuk pengguna yang mudah terdistraksi atau sulit berkonsentrasi.',
                'duration_minutes' => 5,
                'steps' => [
                    'Pilih satu anchor, misalnya sensasi napas di ujung hidung.',
                    'Pertahankan perhatian pada anchor tanpa mengejar pikiran lain.',
                    'Saat perhatian berpindah, beri label sederhana lalu kembali ke anchor.',
                    'Tutup dengan menyadari seluruh tubuh dan lingkungan.',
                ],
                'cues' => ['Pilih anchor', 'Fokus', 'Kembali', 'Penutup'],
                'best_for' => ['distraksi', 'sulit konsentrasi', 'sering mengecek ponsel', 'fokus belajar'],
                'sort_order' => 7,
            ],
            [
                'title' => 'Sitting Meditation',
                'category' => 'sitting_meditation',
                'description' => 'Meditasi duduk untuk menyadari napas, suara, tubuh, pikiran, dan emosi.',
                'knowledge' => 'Sitting meditation membantu membaca pikiran dan emosi tanpa langsung ikut terseret. Dalam MBSR, latihan ini menguatkan non-judging, patience, dan acceptance.',
                'duration_minutes' => 10,
                'steps' => [
                    'Duduk nyaman dengan punggung tegak tetapi tidak kaku.',
                    'Letakkan perhatian pada napas.',
                    'Sadari tekanan kursi, kaki, tangan, dan bahu.',
                    'Dengarkan suara tanpa menilai.',
                    'Sadari pikiran yang muncul tanpa mengikuti ceritanya.',
                    'Sadari emosi yang hadir.',
                    'Kembali ke napas dan lingkungan.',
                ],
                'cues' => ['Posisi tubuh', 'Napas', 'Tubuh', 'Suara', 'Pikiran', 'Emosi', 'Penutup'],
                'best_for' => ['banyak pikiran', 'stres', 'kewalahan'],
                'sort_order' => 8,
            ],
            [
                'title' => 'Body Scan Singkat',
                'category' => 'body_scan_micro',
                'description' => 'Memindai tubuh dari kepala sampai kaki untuk mengenali ketegangan dan kebutuhan istirahat.',
                'knowledge' => 'Body scan membantu tubuh memberi informasi yang sering terlewat saat aktivitas padat. Latihan ini cocok ketika mood checkout negatif, lelah, atau jurnal menunjukkan beban emosional.',
                'duration_minutes' => 10,
                'steps' => [
                    'Duduk atau berbaring nyaman dan sadari beberapa napas.',
                    'Sadari telapak kaki, jari kaki, suhu, dan berat tubuh.',
                    'Sadari betis, lutut, dan paha.',
                    'Sadari panggul dan punggung bawah.',
                    'Sadari gerakan perut saat bernapas.',
                    'Sadari naik turunnya dada.',
                    'Sadari jari, telapak, pergelangan, dan lengan.',
                    'Sadari bahu dan leher tanpa memaksa tegang hilang.',
                    'Sadari rahang, pipi, mata, dahi, dan kepala.',
                    'Sadari tubuh sebagai satu kesatuan dan kembali ke napas.',
                ],
                'cues' => ['Persiapan', 'Kaki', 'Tungkai', 'Panggul', 'Perut', 'Dada', 'Tangan', 'Bahu', 'Wajah', 'Seluruh tubuh'],
                'best_for' => ['lelah', 'tegang', 'mood negatif', 'pemulihan'],
                'sort_order' => 9,
            ],
            [
                'title' => 'Body Scan Penuh',
                'category' => 'body_scan_full',
                'description' => 'Versi lebih panjang untuk tekanan tinggi dan pemulihan lebih dalam.',
                'knowledge' => 'Body scan penuh dipakai saat sinyal burnout tinggi. Latihan ini memberi ruang pemulihan lebih panjang dan sebaiknya dilakukan di tempat aman, tenang, dan tidak terburu-buru.',
                'duration_minutes' => 20,
                'steps' => [
                    'Duduk atau berbaring nyaman dan sadari beberapa napas.',
                    'Sadari telapak kaki, jari kaki, suhu, dan berat tubuh.',
                    'Sadari betis, lutut, dan paha.',
                    'Sadari panggul dan punggung bawah.',
                    'Sadari gerakan perut saat bernapas.',
                    'Sadari naik turunnya dada.',
                    'Sadari jari, telapak, pergelangan, dan lengan.',
                    'Sadari bahu dan leher tanpa memaksa tegang hilang.',
                    'Sadari rahang, pipi, mata, dahi, dan kepala.',
                    'Sadari tubuh sebagai satu kesatuan dan kembali ke napas.',
                ],
                'cues' => ['Persiapan', 'Kaki', 'Tungkai', 'Panggul', 'Perut', 'Dada', 'Tangan', 'Bahu', 'Wajah', 'Seluruh tubuh'],
                'best_for' => ['burnout tinggi', 'kelelahan emosional', 'pemulihan panjang'],
                'sort_order' => 10,
            ],
            [
                'title' => 'Mindful Movement',
                'category' => 'mindful_movement',
                'description' => 'Peregangan ringan dengan perhatian penuh pada gerak, napas, dan batas nyaman tubuh.',
                'knowledge' => 'Mindful movement cocok ketika tekanan terasa menumpuk di tubuh. Latihan ini bukan olahraga berat, melainkan cara bergerak perlahan sambil mendengar batas tubuh.',
                'duration_minutes' => 10,
                'steps' => [
                    'Berdiri atau duduk dengan ruang gerak aman.',
                    'Naikkan dan turunkan bahu perlahan.',
                    'Putar bahu jika terasa nyaman.',
                    'Angkat tangan perlahan tanpa memaksa.',
                    'Gerakkan leher perlahan ke kanan dan kiri.',
                    'Sadari punggung atas saat bergerak.',
                    'Sadari pinggang dan kaki dengan gerakan ringan.',
                    'Rasakan kondisi tubuh sebelum lanjut.',
                ],
                'cues' => ['Grounding', 'Bahu naik-turun', 'Putar bahu', 'Angkat tangan', 'Leher', 'Punggung atas', 'Pinggang dan kaki', 'Penutup'],
                'best_for' => ['pegal', 'duduk lama', 'usaha tinggi', 'lelah fisik'],
                'sort_order' => 11,
            ],
            [
                'title' => 'Walking Meditation',
                'category' => 'walking_meditation',
                'description' => 'Berjalan perlahan sambil menyadari kontak kaki, napas, dan lingkungan.',
                'knowledge' => 'Walking meditation membantu saat tubuh butuh jeda aktif. Latihan ini cocok setelah belajar atau mengajar lama, terutama ketika duduk diam terasa sulit.',
                'duration_minutes' => 5,
                'steps' => [
                    'Berdiri dan sadari kontak kaki dengan lantai.',
                    'Mulai berjalan perlahan di jalur yang aman.',
                    'Sadari gerakan angkat, gerak, dan sentuh pada kaki.',
                    'Sadari gerakan seluruh tubuh saat berjalan.',
                    'Hubungkan napas dengan langkah.',
                    'Sadari lingkungan sekitar tanpa terburu-buru menilai.',
                    'Perlambat langkah, berhenti, lalu tutup sesi.',
                ],
                'cues' => ['Berdiri', 'Mulai berjalan', 'Angkat-gerak-sentuh', 'Tubuh', 'Napas', 'Lingkungan', 'Penutup'],
                'best_for' => ['jenuh', 'duduk lama', 'transisi', 'gelisah'],
                'sort_order' => 12,
            ],
            [
                'title' => 'Open Monitoring',
                'category' => 'open_monitoring',
                'description' => 'Mengamati pengalaman apa pun yang muncul tanpa memilih, mengejar, atau langsung bereaksi.',
                'knowledge' => 'Open Monitoring atau Choiceless Awareness membantu saat pikiran ramai dan emosi bercampur. Pengguna belajar melihat pikiran, suara, emosi, dan sensasi sebagai pengalaman yang datang dan pergi.',
                'duration_minutes' => 10,
                'steps' => [
                    'Stabilkan diri melalui napas.',
                    'Buka awareness ke tubuh.',
                    'Sadari suara yang muncul.',
                    'Sadari pikiran dan emosi tanpa mengejar atau menolak.',
                    'Biarkan pengalaman datang dan pergi dalam kesadaran terbuka.',
                    'Kembali ke napas untuk menutup sesi.',
                ],
                'cues' => ['Stabil', 'Tubuh', 'Suara', 'Pikiran dan emosi', 'Kesadaran terbuka', 'Penutup'],
                'best_for' => ['overwhelmed', 'pikiran ramai', 'emosi bercampur', 'non-reactivity'],
                'sort_order' => 13,
            ],
            [
                'title' => 'Mindfulness of Sounds',
                'category' => 'mindfulness_of_sounds',
                'description' => 'Menggunakan suara sebagai anchor perhatian tanpa memberi label baik, buruk, atau mengganggu.',
                'knowledge' => 'Mindfulness of Sounds cocok sebagai alternatif bagi pengguna yang kurang nyaman fokus pada napas. Suara dipakai untuk grounding dan mengembalikan awareness.',
                'duration_minutes' => 5,
                'steps' => [
                    'Siapkan posisi yang nyaman.',
                    'Dengarkan suara dekat tanpa menilai.',
                    'Dengarkan suara jauh tanpa mengejar sumbernya.',
                    'Sadari suara muncul, berubah, dan menghilang.',
                    'Kembali pada napas dan tutup sesi.',
                ],
                'cues' => ['Persiapan', 'Suara dekat', 'Suara jauh', 'Muncul berubah hilang', 'Napas'],
                'best_for' => ['grounding', 'sulit fokus', 'pikiran bergerak terus', 'latihan ringan'],
                'sort_order' => 14,
            ],
            [
                'title' => 'RAIN',
                'category' => 'rain_self_compassion',
                'description' => 'Recognize, Allow, Investigate, Nurture untuk emosi yang berat.',
                'knowledge' => 'RAIN membantu ketika emosi terasa kuat. Teknik ini melatih mengenali emosi, mengizinkan ia hadir, menyelidiki sensasi tubuh, lalu memberi respons yang penuh welas asih.',
                'duration_minutes' => 7,
                'steps' => [
                    'Recognize: kenali emosi yang sedang muncul.',
                    'Allow: izinkan emosi hadir tanpa dilawan.',
                    'Investigate: rasakan di bagian tubuh mana emosi itu muncul.',
                    'Nurture: beri kalimat baik untuk diri sendiri.',
                    'Pilih satu langkah kecil yang aman setelah latihan.',
                ],
                'cues' => ['Kenali', 'Izinkan', 'Selidiki', 'Rawat'],
                'best_for' => ['sedih', 'marah', 'frustrasi', 'tekanan emosional'],
                'sort_order' => 15,
            ],
            [
                'title' => 'Loving-Kindness Meditation',
                'category' => 'loving_kindness',
                'description' => 'Latihan niat baik kepada diri sendiri dan orang lain secara perlahan.',
                'knowledge' => 'Loving-kindness cocok saat merasa keras pada diri sendiri, konflik, atau rendah pencapaian diri. Latihan ini membantu membangun self-compassion tanpa memaksa emosi positif muncul.',
                'duration_minutes' => 7,
                'steps' => [
                    'Stabilkan diri dengan napas dan posisi tubuh.',
                    'Arahkan kalimat baik kepada diri sendiri.',
                    'Arahkan niat baik kepada orang yang dipercaya.',
                    'Perluas kebaikan kepada orang lain jika nyaman.',
                    'Kembali ke napas dan tubuh untuk menutup sesi.',
                ],
                'cues' => ['Stabil', 'Diri sendiri', 'Orang dipercaya', 'Perluas', 'Penutup'],
                'best_for' => ['rendah pencapaian diri', 'konflik', 'sedih', 'self-compassion'],
                'sort_order' => 16,
            ],
            [
                'title' => 'Mountain Meditation',
                'category' => 'mountain_meditation',
                'description' => 'Meditasi visualisasi gunung sebagai metafora kestabilan saat lingkungan dan emosi berubah.',
                'knowledge' => 'Mountain Meditation membantu pengguna menghadapi perubahan, emosi naik-turun, dan tekanan tinggi dengan mengembangkan acceptance dan perspektif bahwa pikiran serta emosi dapat berubah.',
                'duration_minutes' => 15,
                'steps' => [
                    'Mulai dengan persiapan tubuh dan napas.',
                    'Bayangkan bentuk gunung yang kokoh.',
                    'Bayangkan cuaca berubah di sekitar gunung.',
                    'Hubungkan perubahan cuaca dengan perubahan pikiran dan emosi.',
                    'Rasakan kestabilan tubuh.',
                    'Kembali pada napas dan tutup sesi.',
                ],
                'cues' => ['Napas', 'Gunung', 'Cuaca', 'Emosi berubah', 'Stabil', 'Penutup'],
                'best_for' => ['emosi naik turun', 'tidak stabil', 'perubahan', 'tekanan tinggi', 'acceptance'],
                'sort_order' => 17,
            ],
            [
                'title' => 'Informal Mindfulness',
                'category' => 'informal_mindfulness',
                'description' => 'Latihan mindfulness dalam aktivitas sehari-hari seperti minum, makan, atau berjalan menuju kelas.',
                'knowledge' => 'Informal Mindfulness membangun kebiasaan hadir tanpa harus membuka sesi meditasi formal. Teknik ini cocok untuk prevention, maintenance, dan pengguna dengan waktu terbatas.',
                'duration_minutes' => 3,
                'steps' => [
                    'Pegang gelas dan sadari suhu pada tangan.',
                    'Perhatikan warna dan aroma minuman.',
                    'Minum perlahan dengan perhatian penuh.',
                    'Sadari sensasi setelah menelan.',
                    'Perhatikan warna, bentuk, dan aroma makanan.',
                    'Ambil satu suapan secara sadar.',
                    'Kunyah perlahan tanpa terburu-buru.',
                    'Sadari rasa dan tekstur makanan.',
                    'Sadari kondisi tubuh setelah makan.',
                    'Saat berjalan ke kelas, sadari langkah kaki.',
                    'Sadari napas selama berjalan.',
                    'Sadari lingkungan sekitar tanpa membuka ponsel jika memungkinkan.',
                ],
                'cues' => ['Pegang gelas', 'Warna dan aroma', 'Minum', 'Sensasi', 'Makanan', 'Suapan', 'Kunyah', 'Rasa', 'Tubuh', 'Langkah', 'Napas', 'Lingkungan'],
                'best_for' => ['waktu terbatas', 'maintenance', 'pencegahan', 'rutinitas harian'],
                'sort_order' => 18,
            ],
            [
                'title' => 'Jurnal Reflektif Harian',
                'category' => 'reflective_journal',
                'description' => 'Menulis satu hal yang menguras energi dan satu hal kecil yang bisa dilepaskan.',
                'knowledge' => 'Jurnal reflektif membantu mengubah pengalaman harian menjadi informasi. Teknik ini cocok setelah check-out agar rekomendasi berikutnya makin sesuai dengan pola yang muncul.',
                'duration_minutes' => 5,
                'steps' => [
                    'Tulis satu hal yang paling menguras energi hari ini.',
                    'Tulis satu perasaan yang paling dominan.',
                    'Tulis pola yang mulai terlihat.',
                    'Tulis satu hal kecil yang bisa dilepaskan atau ditunda.',
                    'Tutup dengan rencana lembut untuk besok.',
                ],
                'cues' => ['Fakta', 'Perasaan', 'Pola', 'Rencana'],
                'best_for' => ['refleksi', 'pola jurnal', 'rendah pencapaian diri'],
                'sort_order' => 19,
            ],
        ];

        MindfulTactic::whereNotIn('category', array_column($tactics, 'category'))->delete();

        foreach ($tactics as $tactic) {
            MindfulTactic::updateOrCreate(
                ['category' => $tactic['category']],
                $tactic,
            );
        }
    }
}
